eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: fegin-loadbalance
feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true