eureka:
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zuul-route
zuul:
  routes:
    ribbon:
      path: /api-ribbon/**
      serviceId: RIBBON-LOADBALANCE

    fegin:
      path: /api-fegin/**
      serviceId: FEGIN-LOADBALANCE
